version: "3"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Hybris!nimda"
      ACCEPT_EULA: "Y"
    # volumes:
    #  - mssqldb-vol:/var/opt/mssql
  mssqlinit:
    image: "mcr.microsoft.com/mssql-tools"
    volumes: 
      - /Users/i839873/Innos/cloud-commerce-sample-setup/docker-resources:/tmp/resources
    command: /tmp/resources/wait-for-it/wait-for-it.sh -t 120 mssql:1433 -- bash -c "/opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Hybris!nimda" -i /tmp/resources/db_init.sql"
    depends_on:
      - mssql
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports: 
      - 10000:10000
    # volumes: 
    #   - azurite-store:/data
volumes:
  resources_vol:
    driver_opts:
      type: none
      device: ${PWD}/docker-resources
      o: bind
#   mssqldb-vol:
#   azurite-store:

